### ISSUE TITLE
Two /tmp/xapp-tmp-*.png files created when app update self icon

### ISSUE THREAD

**Issue by dafanasiev** [linuxmint/xapp#106]
I use telegram desktop and this app update self icon when i have unread messages. In this case I see two png files in `/tmp`.

This files created here : [sn-item.c#L402](https://github.com/linuxmint/xapp/blob/9c4d5e92d2eb288463f97f65bf7367ac4933af34/xapp-sn-watcher/sn-item.c#L402)

Does this files really need to be present ? 
May by its safe to remove file after `xapp_status_icon_set_icon_name()` call ?

**Comment by LinuxOnTheDesktop** [comment]
I have the same or a similar problem: the program [angrySearch](https://github.com/DoTheEvo/ANGRYsearch/blob/master/angrysearch.desktop) is generating a load of tmp icons files:

```
/tmp $ ls -all xapp*
-rw-rw-r-- 1 <me> <me> 334 Aug 30 01:24 xapp-tmp-0x5568e5fef4c0-1.png
-rw-rw-r-- 1 <me> <me> 334 Aug 30 00:54 xapp-tmp-0x5568e5fef540-1.png
-rw-rw-r-- 1 <me> <me> 334 Aug 30 03:47 xapp-tmp-0x5568e5fef5c0-1.png
-rw-rw-r-- 1 <me> <me> 334 Aug 30 02:14 xapp-tmp-0x5568e61f3030-1.png
-rw-rw-r-- 1 <me> <me> 334 Aug 30 02:28 xapp-tmp-0x5568e61f3130-1.png
-rw-rw-r-- 1 <me> <me> 334 Aug 30 01:38 xapp-tmp-0x5568e61f3330-1.png
-rw-rw-r-- 1 <me> <me> 334 Aug 30 01:45 xapp-tmp-0x5568e61f34b0-1.png
-rw-rw-r-- 1 <me> <me> 334 Aug 30 04:31 xapp-tmp-0x5568e61f36b0-1.png
-rw-rw-r-- 1 <me> <me> 334 Aug 31 04:57 xapp-tmp-0x55c46d3c4e10-1.png
-rw-rw-r-- 1 <me> <me> 334 Aug 30 06:46 xapp-tmp-0x55cd2f8b8e00-1.png
-rw-rw-r-- 1 <me> <me> 334 Aug 30 05:42 xapp-tmp-0x55cd2f97ed80-1.png
-rw-rw-r-- 1 <me> <me> 334 Sep  4 17:53 xapp-tmp-0x55d13badd930-1.png
-rw-rw-r-- 1 <me> <me> 334 Sep  2 03:29 xapp-tmp-0x55e365b60dc0-1.png
-rw-rw-r-- 1 <me> <me> 334 Sep  2 03:58 xapp-tmp-0x55e365bcd990-1.png
-rw-rw-r-- 1 <myOtherUser>  <myOtherUser>  334 Aug 30 04:38 xapp-tmp-0x55f71f0d9aa0-1.png
-rw-rw-r-- 1 <me> <me> 334 Sep  5 05:11 xapp-tmp-0x5602f246d5b0-1.png
-rw-rw-r-- 1 <myOtherUser>  <myOtherUser>  334 Sep  6 02:13 xapp-tmp-0x560604105b80-1.png
-rw-rw-r-- 1 <me> <me> 334 Aug 30 02:19 xapp-tmp-0x7f649c01b140-1.png
-rw-rw-r-- 1 <me> <me> 334 Sep  4 04:24 xapp-tmp-0x7f64d40318a0-1.png
-rw-rw-r-- 1 <me> <me> 334 Sep  1 04:29 xapp-tmp-0x7fc76401a000-1.png
```


A new file gets created every time I run angrySearch.

**Comment by mtwebster** [comment]
No it's not safe to remove.

The image is written to a temp file so the xapp status applet can be passed a path (asynchronously) and load the image. That image needs to remain until the application itself decides to change the icon. Two files are used because there is delay between the app and applet when updating icons, so it alternates between -0.png and -1.png.

I can clean up the tmp folder when the xapp-sn-watcher exits. I'll also have it use /dev/shm (which is a ramdisk) if available.

**Comment by LinuxOnTheDesktop** [comment]
> I can clean up the tmp folder when the xapp-sn-watcher exits.

Sounds good. Thanks.

> I'll also have it use /dev/shm (which is a ramdisk) if available.

Even better (so long as the ramdisk does not get full!). (Also, for what it is worth: I checked on one of my systems and that system seems to lack `/dev/shm`.)

**Comment by LinuxOnTheDesktop** [comment]
Ah: /dev/shm is known also as 'tmpfs'.

```
$ df -k /dev/shm
Filesystem     1K-blocks  Used Available Use% Mounted on
tmpfs            3976628     0   3976628   0% /dev/shm
```

Thank you for fixing this problem.

**Comment by mtwebster** [comment]
It'll fall back to using /tmp if there's no ramdisk.

Although theoretically possible, it's pretty unlikely these will end up taking enough space to cause an issue - each process will create 2 icons at most (and they're only generated under certain circumstances only). And now that we're attempting to remove them as well, I think we'll be ok there.

I'm curious if you could tell me what system is the one without /dev/shm (we've discussed this internally in the past and were pretty sure about it being used on most, if not all, distros.

**Comment by LinuxOnTheDesktop** [comment]
@mtwebster 

Our posts crossed in the ether. It turns out I _do_ have /dev/shm - please see my post above (i.e., [this one](https://github.com/linuxmint/xapp/issues/106#issuecomment-1242422733)).

**Comment by mtwebster** [comment]
Ah ok good - I guess we weren't wrong (at least for now).
