### ISSUE TITLE
LMDE 4 - redshift icon not visible in taskbar

### ISSUE THREAD

**Issue by Mar-tux** [linuxmint/xapp#107]
Hello everyone, :)

since 14.08.2020 there is an issue with the icon for redshift. It is not visible anymore. There es a free space in the taskbar. Doing a right click on it, the redshift menu is opening.
So the program itself is working but the icon is missing. This error only occured when using the Mint-Y theme.

Maybe the problem is located in the xapps - the error occured after the following updates on 14.08.2020:

xapps-common
libxapp1
gir1.2-xapp-1.0

![redshift-icon-missing](https://user-images.githubusercontent.com/69798353/90528399-dab46c00-e172-11ea-82e5-3b06d181d35d.png)

**Comment by marco4mp** [comment]
@Mar-tux I think it's time to close this issue. Currently in LMDE 6 the icon looks ok.

**Comment by Mar-tux** [comment]
> @Mar-tux I think it's time to close this issue. Currently in LMDE 6 the icon looks ok.

You're right. I had already forgotten that.  Thanks for the reminder.  :-)
