### ISSUE TITLE
xapp-sn-watcher.desktop loses entries after being toggled off and on a few times

### ISSUE THREAD

**Issue by Harry-W-Haines-III** [linuxmint/xapp#129]
If you toggle this off and on and off again several times in System Settings | Startup Applications, the line item turns to "Unavailable" "No Description".  See attached screen shot.  Looking at the file xapp-sn-watcher.desktop showed:

[Desktop Entry]
Type=Application
Exec=/bin/false
X-GNOME-Autostart-enabled=false

Failure is repeatable.  Once the desktop file loses entries, it won't change again to what it should be.
Seems the action should just be to change X-GNOME-Autostart-enabled=true to false and back again.

![Screenshot-from-2021-01-12-14-51-41](https://user-images.githubusercontent.com/45599505/104366107-df453c80-54e6-11eb-9ae6-9452f442049d.png)

Wasn't sure to file it here or under Cinnamon.  If its filed in the wrong place, please move it.

**Comment by mtwebster** [comment]
Is this with cinnamon 4.8? I can't reproduce this. Can you make this happen with other entries as well or just xapps?

**Comment by Harry-W-Haines-III** [comment]
It is with Cinnamon 4.8.5 and it happened on two computers.  If you toggle it multiple times, close the window and come back, the entry shows "Unavailable".  I have checked for some other entries on the than xapp-sn-watcher.  Haven't reproduced it on them.

**Comment by Harry-W-Haines-III** [comment]
Just to assist.  I booted to a live USB session.  It's clearly reproducible  OFF-ON-OFF, close the System Settings window.  Open again, go to Startup Applications and its missing.

**Comment by Harry-W-Haines-III** [comment]
While we are on this subject of items in Startup Applications, what is "IM Launch" "No description"?  This seems to pertain to a Wayland session.  By default it is turned on.  Is this just part of the open desktop ecosystem or something from Ubuntu that isn't really needed in Mint?  If it is required, perhaps the desktop item could be better documented so it would show its purpose in Startup Applications.

**Comment by Harry-W-Haines-III** [comment]
Has anyone been able to reproduce this?

**Comment by nathan818fr** [comment]
The same happened to me.
```
OS: Debian GNU/Linux bullseye x86_64
Kernel: 5.10.0-1-amd64
DE: Cinnamon 4.8.6
```

**Comment by Harry-W-Haines-III** [comment]
Has this been looked at any further?

**Comment by mtwebster** [comment]
I finally managed to reproduce it, thanks.

We don't add (or need) im-launch, it is something from ubuntu. But there's nothing stopping a mint user from setting up gnome-shell or something else that uses wayland/xwayland. Under the default mint desktops it won't ever do anything either way.
