### ISSUE TITLE
Failed to load module “xapp-gtk3-module”

### ISSUE THREAD

**Issue by munavi** [linuxmint/xapp#134]
Hello,

I try to start my JavaFX Application in InteliJDEA and it was always this message: "Gtk- Message: time: Failed to load module “xapp-gtk3-module”.  I have Linux Mint 20.1 Cinnamon and System:    Kernel: 5.8.0-48-generic x86_64 bits: 64 compiler: N/A Desktop: Cinnamon 4.8.6 

Can you say please what should I do?

Than you very much!

**Comment by icarter09** [comment]
Does this occur for every Java application you start via IntelliJ or is it only ones using JavaFX? Also could you provide the steps to reproduce this and a screen shot of the issue? Thanks.

**Comment by mtwebster** [comment]
It's completely harmless, you can ignore it. If it happens with all other programs as well (like nemo), there may be some issue, but nothing harmful.

What xapp-gtk3-module does:
In Mint 20.1 we added support for 'favorite' files, and part of that support was to make a "Favorites" bookmark visible in the file open/save dialogs of many programs (any that use Gtk3) - that's the primary thing this module is for, it installs a hook that adds that bookmark, along with underlying support for it. If for whatever reason it gives this message, it means that program was unable to load that particular module, which means the favorite shortcut would unavailable.

I've seen this happen on QT programs (where it's useless anyhow), so it's possible it would occur with your application as well.

https://github.com/linuxmint/xapp/blob/master/libxapp/xapp-gtk3-module.c

**Comment by munavi** [comment]
Thank you very much. I have started to run my application, the error remains. Apparently it was my personal mistake, because I created a new project and it worked. Sorry for the inconvenience.

**Comment by claudio-exe** [comment]
Same problem here. When i try tu run my intelliJ project i get the error: failed to load "xapp-gtk3-module".
