### ISSUE TITLE
RFE: allow build xapp without dbusmenu-gtk3-0.4

### ISSUE THREAD

**Issue by kloczek** [linuxmint/xapp#138]
libdbusmenu is no longer maintained and last change has been made in that project ~5 years ago.

**Comment by mtwebster** [comment]
You can skip it in your build using a meson option: `-D status-notifier=false`. You will lose StatusNotifier support.

I'm not removing it entirely until I have time to re-implement how our status icon menus are shown.

**Comment by kloczek** [comment]
OK closing.

Thank you.
