### ISSUE TITLE
XAPP_FORCE_GTKWINDOW_ICON doesn't work anymore on Debian Testing XFCE

### ISSUE THREAD

**Issue by ivan-hc** [linuxmint/xapp#145]
I have some custom profiles with Firefox, after updating at version 92 XAPP_FORCE_GTKWINDOW_ICON doesn't work anymore. I've tested this on other programs and this doesn't work too. Now I've updated libxapp1 from the Debian Experimental branch and it doesn't work too. I don't know if this depends on other libraries from Debian Testing/Unstable, but now I'm unable to use a different icon in my webapps when they are opened (titlebar and xfce-panel). How to solve?

**Comment by mtwebster** [comment]
This functionality depends on a gtk3 module - 

Is your environment set to use it?:
```
> env | grep GTK3
GTK3_MODULES=xapp-gtk3-module
```
That gets defined by this file when the session starts:
```
/etc/X11/xinit/xinitrc.d/80xapp-gtk3-module.sh
```
The appropriate location for that file has changed over time - who knows, maybe it changed again, I have no idea about debian experimental.

The actual module should be installed here:
```
/lib/x86_64-linux-gnu/gtk-3.0/modules/libxapp-gtk3-module.so
```

If you start these apps in a terminal does it say 'Failed to load ... module'?

**Comment by ivan-hc** [comment]
Hi

> Is your environment set to use it?:

> `> env | grep GTK3`
`GTK3_MODULES=xapp-gtk3-module`

> That gets defined by this file when the session starts:

> `/etc/X11/xinit/xinitrc.d/80xapp-gtk3-module.sh`


I've not xinitrc.d/80xapp-gtk3-module.sh in /etc/X11/xinit/, should I create it?

Starting these apps in the terminal I've no messages, it will opened in Firefox normally (with the firefox icon).

**Comment by mtwebster** [comment]
it's GTK3_MODULES, not GTK_MODULES.

That file should be installed by the package

It looks like the debian guys may have missed a change a while back:
https://github.com/linuxmint/xapp/commit/cba181dedeab3aa04aa5327e824d048dd8ed85cd#diff-ee0d750477d547a86d51c7a857402ca2dda7aed3d3f130978183d81ef204f9c2

The init file may not be getting installed:
https://salsa.debian.org/cinnamon-team/xapp/-/blob/master/debian/xapps-common.install#L8

Check etc/X11/Xsession.d to see if that file is there (`80xapp-gtk3-module.sh`) - if it is, try copying it to /etc/X11/xinit/xinitrc.d and make sure it's executable.

**Comment by mtwebster** [comment]
That file may not be installed anywhere, actually - you can get it here: https://raw.githubusercontent.com/linuxmint/xapp/master/data/80xapp-gtk3-module.sh and copy it into the location I said. Make sure it's executable.

**Comment by ivan-hc** [comment]
80xapp-gtk3-module.sh is in etc/X11/Xsession.d without flag "executable".
I've copied it to /etc/X11/xinit/xinitrc.d/ and now both are executable.
I've rebooted the PC but no custom icon appear on my webapps.

**Comment by ivan-hc** [comment]
UPDATE: XAPP_FORCE_GTKWINDOW_ICON works for other programs, not Firefox

**Comment by mtwebster** [comment]
No idea - works for me on Mint here with ff 92 - are you running it in a sandbox? Flatpak version?

**Comment by ivan-hc** [comment]
UPDATE2 - I've removed /etc/X11/xinit/xinitrc.d/80xapp-gtk3-module.sh, rebooted and re-tried with another program: `XAPP_FORCE_GTKWINDOW_ICON=gmail gedit` opens gedit with the icon of gmail. So the problem belong to Firefox.

**Comment by ivan-hc** [comment]
> are you running it in a sandbox? Flatpak version?
No, this is the official bundle from the official website of Mozilla. It worked well until the update to Firefox 92.

**Comment by ivan-hc** [comment]
I've found this in /nome/$USER/.xsession-error:

`(polkit-gnome-authentication-agent-1:1113): polkit-gnome-1-WARNING **: 17:17:18.813: Unable to get a pixbuf for GTK_STOCK_DIALOG_AUTHENTICATION (gtk-dialog-authentication) at size 48`
`Gtk-Message: 17:17:23.855: Failed to load module "xapp-gtk3-module"`
`Gtk-Message: 17:17:23.870: Failed to load module "xapp-gtk3-module"`
`Gtk-Message: 17:17:23.892: Failed to load module "xapp-gtk3-module"`

**Comment by mtwebster** [comment]
is GTK3_MODULES in the environment when firefox launches?

what about:
```
GTK3_MODULES=xapp-gtk3-module XAPP_FORCE_GTKWINDOW_ICON=gmail firefox
```

**Comment by ivan-hc** [comment]
tried `GTK3_MODULES=xapp-gtk3-module XAPP_FORCE_GTKWINDOW_ICON=gmail firefox --class WebApp-Gmail --profile /home/$USER/.mozilla/firefox/gmail https://gmail.com`, nothing happens (the browser starts in gmail.com with the gmail profile, but still with the firefox icon).

**Comment by mtwebster** [comment]
Ah I'm on cinnamon, this is why it works for me (the xapp thing here is for mate and xfce only). I'll have to have a look at what got changed. It was definitely ok in 91?

**Comment by jashimkhan2215** [comment]
Kaios Geophone T19 IMEI

**Comment by jashimkhan2215** [comment]
Welcome to Gboard clipboard, any text you copy will be saved here.

**Comment by jashimkhan2215** [comment]
[ftpd (1).zip](https://github.com/linuxmint/xapp/files/7876767/ftpd.1.zip)
[Xbox Live (profile, achievements and friends online).zip](https://github.com/linuxmint/xapp/files/7876768/Xbox.Live.profile.achievements.and.friends.online.zip)
[DuckDuckGo - privacy search engine.zip](https://github.com/linuxmint/xapp/files/7876769/DuckDuckGo.-.privacy.search.engine.zip)

**Comment by jashimkhan2215** [comment]
[adbroot.zip](https://github.com/linuxmint/xapp/files/7876770/adbroot.zip)

**Comment by jashimkhan2215** [comment]
[ftpd (1).zip](https://github.com/linuxmint/xapp/files/7876772/ftpd.1.zip)

**Comment by jashimkhan2215** [comment]
[store.zip](https://github.com/linuxmint/xapp/files/7876773/store.zip)

**Comment by jashimkhan2215** [comment]
[KaiOS-Boilerplate-Company-Profile.zip](https://github.com/linuxmint/xapp/files/7876775/KaiOS-Boilerplate-Company-Profile.zip)

**Comment by jashimkhan2215** [comment]
[Shopee.zip](https://github.com/linuxmint/xapp/files/7876779/Shopee.zip)
