### ISSUE TITLE
Old panel issue strikes again and again. 10 years without solution

### ISSUE THREAD

**Issue by invernosantigos** [linuxmint/xapp#151]
Well, this is my last attempt to solve an old Cinnamon bug that is not only annoying but also frustrating. There have been complaints about him since the retired Mint Rebecca days, and countless petitions on forums for solutions, awaiting a response for years. It will probably end up like certain bugs, which instead of being fixed, disappear just because they became obsolete! Bad development sign... Or, very soon, he will be of legal age, and users will be able to sue the bug himself criminally.
        The bug is an old problem about the size of panel indicators. After an uninstall, accidental or not, of the panel ( and Cinammon facilitates accidental uninstallation of the panel, because when creating a New Panel by mistake or just out of curiosity, it is not possible to cancel the operation, and the user goes ahead thinking about uninstalling the new panel later. But the system screw up, uninstalling both, or uninstalls only one and loses the settings of both. ). Well, coming back, after an accidental uninstall (or not) of the panel, and its reinstallation, the Panel Indicators ( old icons linked to X11 < like this, explained to me, if not, please correct this from X11 > inherited from versions old pre-xapp like Sound-indicator, Network-Manager, Recents, Power, Printers, Notifications; these things, generically called Indicators-Panel (name of an old package they came in in Mint Rebecca days and such... ) After reinstalling the panel, these indicators-panel get their sizes altered; usually super size on reinstallation, but in some bugs that are frequent until today, they just disappear, but leave an empty space in the panel location, so that could be a bug of "Zero Size", that is, the icon disappears because its size deconfigured and became zero, or it could even be an icon-path problem, why not?
        
        Some examples just here from the current Github:
      https://github.com/linuxmint/xapp/issues/113
      https://github.com/linuxmint/xapp/issues/139
      https://github.com/linuxmint/xapp/issues/136
      
         Note: Not configurable in System Settings > Panel. There is an additional problem: you can only resize the Xapp icons (the colored ones), this does not affect the Indicators ( Sound-Indicator, Network-Manager, Recents, Power, Notifications, Printers... ) There is no way to configure these separately, and they are not the same size as the others. It's one of Cinnamon's oldest bugs But the biggest problem even there is the ambiguity: there are different names for different types of icons ( "Colorful" < apps and appliccations >, "symbolic icons" < what's this ? > and Indicators ) but there are no tags, examples or manual to say what it is... You have to practically configure it blindly and then look at the result.
         
         There is no icon file that is their source, and maybe they are .svg, there is no way to know! There is also no configuration file for XappNotifier, which is why it does things anyway like in so many bug reports here, like https://github.com/linuxmint/xapp/issues/148  which is on another, but perhaps related, subject. Sometimes using a config file means secure configuration -- as an example, as I've been saying for years, Pulseaudio is a mess, and on top of that ALSA was built on top of it, anyway, as a "tweak" ( irregular annex of a house) of a shack in any favela. All Pulseaudio problems could be solved with the use of a simple confile file, those .cfg files that are used to configure other configuration files (the supreme example is Grub, which is the most stable, reliable and well made in the linux world... ) and by the way, pulse sometimes doesn't load Kernel modules, and there is no sound output, but just write a list of modules in a default.pa file and put it in ~/.config/pulse folder , that all problems resolve themselves naturally... Config files are also good for replacing tmp with session, and maybe that's exactly something like this that's missing. Or maybe I'm just a pain in the ass making drunken hunches...
         
          The most amazing thing is that the error is immune to panel reinstallation and system upgrades. It only goes away with a clean reinstall of the system, but if so, the problem must be in some obscure config file in the home folder -- as it is not affected by dependency reinstallation and only goes away with a clean reinstall. But which ? There doesn't seem to be any. This always sounds like the legendary "hidden configuration", the one that doesn't appear in the manuals.

There was a half-baked solution to replacing icons in
https://www.desenv-web-rp.com/pt/gnome/como-substituir-icones-de-bandeja-para-aplicacoes-em-canela/961483108/
     (it's only in Portuguese, so open it via chrome-translate: https://www.desenv-web-rp.com/pt/gnome/como-substituir-icones-de-bandeja-para-aplicacoes-em-canela/961483108 / )
      But it is obsolete, it was only for i386, and of course it is not reliable, the idea was good, but it was third party package, or fourth package... But someone continued the original project: https://github.com/bilelmoussaoui/sni-qt  ...which requires deprecated dependencies ( bionic beaver ), and there is no indication that it does what www.desenv-web-rp.com suggested. And either way, it would be a patch for a problem that shouldn't even exist.
          
   So the questions, which I want to pose to all developers is: what is the way for the indicator icons? are they vectors ( .svg ) ? In which instance is their size configured? These are the questions I would like to post in a forum for the salvation of suffering souls. As I said, the problem must be in some obscure config file in the home folder, but the developers have never shared their wisdom on this -- it's a mediocre bug and of no importance other than aesthetics, but it's over 10 years old, and as it is, the bug will be obsolete before it is resolved... or become of age  !

**Comment by invernosantigos** [comment]
Let's see... Among the possibilities, the problem with the icons could be because of some installation package, which is removed via "apt autoremove" after installation. This would no doubt explain why an uninstall and reinstallation of the panel causes tampering with the icons, as there would be a missing package that would be responsible for setting them up correctly, but this is the kind of exclusive knowledge of the developers. On the other hand, the hypothesis of "hidden configurations" remains likely, which can be configuration files that exist, but are not included in the manual, or could be a problem of "cross configurations", that is, configurations that are interfering with other configurations. ( this is still "hidden configuration" ). The possibility of configuration files that are not in the manuals is remote, because as I said, they would have to be in the home folder, since the most distinctive feature of the bug is the fact that it can only be fixed by reformatting and reinstalling -clean system **ENTIRE** -- the bug remains if upgraded to a higher version or recovery via timeshift, and what they have in common is that these ways of recovery (timeshift, upgrade and non-clean reinstallation) is that the home folder remains untouched, with all its configuration files untouched, and with it the same configuration files remain, with the same errors, a problem that is even considered classic, and besides, I and several others have already done searches and more searches for panel configuration files in the home folder. If there is one, it is hidden under some unsuspecting name. So it's most likely a cross-configuration error -- some configuration file in the home folder that interferes with qt's configuration. I even have a backup of all my configuration files in the home folder, but reinstalling  **_all_** ( 3Gb ! ) is not a viable option, as it would unconfigure the entire current system, and I wouldn't know **_wich_** to reinstall in a partial reinstallation of them. So, without guidance from someone more knowledgeable about the "panel" subject, there's no way I can move forward.

**Comment by leigh123linux** [comment]
Go and rant somewhere else!
