### ISSUE TITLE
Xapp Status Applets display dupplicate icons

### ISSUE THREAD

**Issue by ineuw** [linuxmint/xapp#157]
```
* Cinnamon 5.4.9
 * Mint Cinnamon 21.0,
 * Onboard Intel graphics with OS included drivers
 * 64 bit
 ```

**Issue**
Xapp Status Applets display duplicate icons 
The apps are autokey-gtk and xfce4-notes
The appearance is random, sometimes it's only one or the other or both at the same time.

**Expected behaviour**
Display a single icon for the above apps

**Other information**
This may be related to the Windows Behavior Settings?? 
The attached image was taken on Cinnamon 20.3, and it reoccurs in Mint 21.0 as well.

**Configuration info - none  - the icons were added to the panel from the menu

```
![duplicate_panel_icons](https://user-images.githubusercontent.com/10367016/184068630-0547819a-2113-44be-84f0-fea8655bcb2f.jpg)
```

**Comment by mtwebster** [comment]
They're probably not showing up in the xapp applet twice, but once there and once in the old system tray applet (Programs will switch between depending on what support is available).

Try putting a 5 or 10s delay on xapp-sn-watcher. It may help prevent this.

I've seen it before though.

**Comment by ineuw** [comment]
Much thanks. Does it matter if it's activated in startup before or after these two apps are loaded?

**Comment by mtwebster** [comment]
Ah do you have those autostarting as well?

Try what I said first. Honestly it depends on the programs and how well-behaved they are. This is generally not the fault of the xapp applet, there are just so many implementations of status icons out there.

I'll test these specific apps when I get a chance.

**Comment by ineuw** [comment]
Much thanks for the help. Attached is the order at startup.

I am a long time user of autokey-gtk. There is the panel/context menu issue since day one in the gtk version. I don't want you to waste your time, unless you want to help them. As for xfce4-notes support, they suffer from the same shortage of developers, and xfce4-notes is not a gnome program, it was pointed out to me. And I agree with them.

![220812_1622_startup apps ordered by startup time](https://user-images.githubusercontent.com/10367016/184452033-32df3794-67ae-4bc2-834a-0a9a07ec1885.jpg)

**Comment by ineuw** [comment]
> Try putting a 5 or 10s delay on xapp-sn-watcher. It may help prevent this.
> 
@mtwebster Again thanks for your attention to this, and perhaps you can write me which libraries and versions needed. I will then check with the knowledgeable on gitter/Autokey and xfce4. I suspect that they are for other shortcomings on the panel.

Disabling x-app-sn-watcher on startup eliminated the duplicate icons. Can you point me to info about delaying as per your comment?

**Comment by ineuw** [comment]
> > Try putting a 5 or 10s delay on xapp-sn-watcher. It may help prevent this.
> 
> @mtwebster Again thanks for your attention to this, and perhaps you can write me which libraries and versions needed. I will then check with the knowledgeable on gitter/Autokey and xfce4. I suspect that they are for other shortcomings on the panel.
> 
> Disabling x-app-sn-watcher on startup eliminated the duplicate icons. Can you point me to info about delaying as per your comment?
This is no longer an issue. The startup delay was set to 6 seconds after the last app and it has not been an issue ever since.

**Comment by mtwebster** [comment]
oops wrong issue # in that commit ^
