### ISSUE TITLE
xapp-sn-watcher reporting erroneous error repetitively

### ISSUE THREAD

**Issue by powerwagon75** [linuxmint/xapp#167]
Running Linux Mint 20.2 with Cinnamon.

Been getting the repetitive error shown in the attached file for a while now. 
`(xapp-sn-watcher:2467): LIBDBUSMENU-GTK-WARNING **: 16:57:03.705: The child-display variable is set to '(null)' but there's a menu, odd?`
It also has a lot of clutter errors that I'm not sure if related or not.

 Checking update history the package **xapps-common** was last updated 11-16-2022 from 2.2.5+una to 2.2.13+una.  Maybe this isn't an xapp issue? (also saw libdbus-1-3 was updated the same day)

I do know I can repeat/cause the message to log by _raising, minimizing, or closing_ a window.  Thought maybe there was something wrong in the system tray area, and deleted two defunct startup items, but that wasn't it. 

Apologies in advance if this is not an xapp issue.  Will gladly run a debug on this, or the libbus, if given the correct syntax to start it with debug. (admittedly not very good with gdb.)

. 
[xsession-errors.pdf](https://github.com/linuxmint/xapp/files/11094583/xsession-errors.pdf)

. 
[inxi_output.pdf](https://github.com/linuxmint/xapp/files/11094605/inxi_output.pdf)

Edit:  the warning is only happening when I do: _raising, minimizing, or closing a window_.   Nothing else seems to be causing it.

**Comment by LinuxOnTheDesktop** [comment]
For my part I see this in my log, though as yet I am unsure how often the warning is generated:

`(xapp-sn-watcher:4535): Gtk-CRITICAL [. .] gtk_widget_set_accel_path: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed`
