### ISSUE TITLE
Failed to load module "xapp-gtk3-module" error

### ISSUE THREAD

**Issue by anaximeno** [linuxmint/xapp#173]
### Distribution

LMDE 6

### Package version

libxapp1 2.6.1+faye

### Frequency

Quite often

### Bug description

The error is being triggered when opening flatpak applications (and maybe on normal applications as well, but I must confirm):

```bash
Gtk-Message: 18:18:47.154: Failed to load module "xapp-gtk3-module"
```

### Steps to reproduce

Try to run a flatpak application through the terminal with the command `flatpak run <application id>`, for example, I got this error while running insomnia `flatpak run rest.insomnia.Insomnia` (please remember that the app must be installed before running the command) and you will see the error in the logs.

### Expected behavior

The module should be loaded successfully.

### Additional information

I don't know what are the consequences of this error, but I also noted that it might be related to some dependency conflict between the Mint Faye packages for the xapp lib and Debian packages for lib xapp. For example [here](https://askubuntu.com/questions/1396739/failed-to-load-module-xapp-gtk3-module) someone suggested installing the xapp package with the command `apt install xapp` but the following is shown:

```
Package xapp is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  xapp-sn-watcher:i386 libxapp-gtk3-module:i386 xapp-sn-watcher libxapp-gtk3-module

E: Package 'xapp' has no installation candidate
```

Or if you try to install the package `libxapp-gtk3-module` (which seems to be the root of the problem):

```
The following NEW packages will be installed:
  libxapp-gtk3-module
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/8,556 B of archives.
After this operation, 39.9 kB of additional disk space will be used.
(Reading database ... 529830 files and directories currently installed.)
Preparing to unpack .../libxapp-gtk3-module_2.4.2-3_amd64.deb ...
Unpacking libxapp-gtk3-module:amd64 (2.4.2-3) ...
dpkg: error processing archive /var/cache/apt/archives/libxapp-gtk3-module_2.4.2-3_amd64.deb (--unpack):
 trying to overwrite '/etc/X11/Xsession.d/80xapp-gtk3-module', which is also in package libxapp1:amd64 2.6.1+faye
Errors were encountered while processing:
 /var/cache/apt/archives/libxapp-gtk3-module_2.4.2-3_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```
The package `libxapp-gtk3-module` I suspect should be installed on the system but it is not being completely installed because of a conflict with the `libxapp1:amd64 2.6.1+faye` package while trying to set `/etc/X11/Xsession.d/80xapp-gtk3-module`.

**Comment by mtwebster** [comment]
Don't try to install libxapp-gtk3-module. It's a Debian package, that module is already installed on your system (or should be):
```
ls -la /usr/lib/x86_64-linux-gnu/gtk-3.0/modules/libxapp-gtk3-module.so
```

You can ignore the error message on flatpaks. Flatpaks don't have access to the host root, but they're picking up the GTK3_MODULES environment variable when they get launched. Flatpaks don't have access to the host root system, including that module.

This is harmless, the module is not required. *Make sure* you end up  with xapp 2.6.1+faye packages after your messing around or you may have further issues.

**Comment by serge-vk** [comment]
I stumbled upon this closed issue because I am getting this error when I try to run `ubuntu-bug` from the console and after that, I get an error message in the console:  
> Gtk-Message: 19:26:37.171: Failed to load module "xapp-gtk3-module"
and an error window "The application Settings has closed unexpectedly".

**Comment by mtwebster** [comment]
try running:
```
unset GTK3_MODULES
```
then run the program.

As I mentioned above, it shouldn't crash anything, it's just a poorly-worded warning. Also, unless you're on Ubuntu, it may not run anyhow.

**Comment by serge-vk** [comment]
Thank you for your recommendation. I am on Ubuntu 24.04. After installing `libxapp-gtk3-module` I was no longer getting the Gtk-Message error, even when running other applications that produced it before (one of them `dconf-editor`). But when running `ubuntu-bug`, I still get "The application Settings has closed unexpectedly" pop-up. I guess, it must be unrelated to `xapp-gtk3-module`.
