### ISSUE TITLE
I tried installing Nemo on Arch and the installation failed because of /usr/bin/pastebin

### ISSUE THREAD

**Issue by DarkReaper231** [linuxmint/xapp#175]
### Distribution

Arch Linux

### Package version

2.8.1

### Graphics hardware in use

NVIDIA GeForce GTX 1060 6GB

### Frequency

Only occasionally

### Bug description

So I was installing Nemo on Arch Linux and it's dependency failed because xapp complained that `/usr/bin/pastebin` already exist.
That's because I made such file myself and it turns out it even does exactly the same thing, isn't it silly?

So I made this script some time ago to quickly upload pastes of files through terminal
```sh
#!/bin/bash

input=$(cat -)
paste_link=$(echo "$input" | curl -s -F 'file=@-' 0x0.st)

echo "$paste_link"
```
I called it pastebin because it is easy to remember, I use 0x0.st because I had an issue with different website which would not echo the paste link for some reason.

Today I installed Nemo and xapp creates the same file, it uses termbin and the script is bit more complex
**I resolved the issue by renaming my version to pastebin.bak**

### Steps to reproduce

Have pastebin already existing and try to install xapp

### Expected behavior

Maybe xapp shouldn't install this file? Why does it need it anyway? If someone installs Nemo, they won't know such script now exists on their filesystem anyway so it is not very useful until you specifically need it and in that case you probably make your own version like me.

**Comment by DarkReaper231** [comment]
If it is important to xapp, call it xapp-paste or something else

**Comment by leigh123linux** [comment]
nemo only uses libxapp, it doesn't need /usr/bin/pastebin to run.

1: File your issue against archlinux xapp package and get them to split the libs
or
2: File the issue against the other app that provides /usr/bin/pastebin
