### ISSUE TITLE
GTK app crashes on a file dialogue

### ISSUE THREAD

**Issue by applecuckoo** [linuxmint/xapp#177]
### Distribution

Mint 21.2

### Package version

2.6.1+victoria

### Graphics hardware in use

Intel TigerLake-LP GT2 [Iris Xe Graphics] 

### Frequency

Only occasionally

### Bug description

When I open a file dialogue on [VGMTrans](https://nightly.link/vgmtrans/vgmtrans/workflows/build/master), the app crashes with an error.

### Steps to reproduce

Open a file dialogue in [VGMTrans](https://nightly.link/vgmtrans/vgmtrans/workflows/build/master) 

### Expected behavior

The file dialogue would actually open.

### Additional information

<details>
<summary>Show error</summary>

``` 
Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /usr/share/icons/Mint-Y/mimetypes/16/image.png: Unrecognized image file format (gdk-pixbuf-error-quark, 3)
Bail out! Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /usr/share/icons/Mint-Y/mimetypes/16/image.png: Unrecognized image file format (gdk-pixbuf-error-quark, 3)
Aborted (core dumped)
```

</details>

I would have installed the xapp Ubuntu package, but apt complains that the version number of the libxapp1 Mint package is too high.

**Comment by leigh123linux** [comment]
gtkk3 provides the file dialogue.
File your issue against vgmtrans or gtk3.
