### ISSUE TITLE
Availability in Ubuntu 24.02

### ISSUE THREAD

**Issue by maravento** [linuxmint/xapp#181]
### Distribution

ubuntu 24.02

### Package version

unknown

### Frequency

Always

### Bug description

Availability in Ubuntu 24.02 repositories

### Steps to reproduce

```
apt install xapp
Error: xapp has no candidate for installation.
```

### Expected behavior

that is available for this distro

**Comment by leigh123linux** [comment]
File your issue at ubuntu

**Comment by mtwebster** [comment]
I'm guessing you really mean 24.04, but also, there is no xapp package, this is the 'source' package's name. The binary packages this produces (such as libxapp1, libxapp-dev, xapps-common) are all available.
