### ISSUE TITLE
Dependency "dbusmenu-gtk3-0.4" not found

### ISSUE THREAD

**Issue by BlackMage2** [linuxmint/xapp#187]
### Distribution

Ubuntu 22.04.3 LTS

### Package version

git head, ebccaa3

### Graphics hardware in use

Intel Ivybridge (Gen7), i7-3520M CPU

### Frequency

Always

### Bug description

The Dependency "dbusmenu-gtk3-0.4" is not found. Are the includes separated from the lib? I have installed libdbusmenu-gtk3-4 (16.04.1+18.10.20180917-0ubuntu8).

### Steps to reproduce

checkout the source and install gir1.2-dbusmenu-gtk3-0.4 and try to build

### Expected behavior

successfull compilation

**Comment by leigh123linux** [comment]
You need to install libdbusmenu-gtk3-dev
