### ISSUE TITLE
Distributing flatpaks

### ISSUE THREAD

**Issue by HugLifeTiZ** [linuxmint/xapp#97]
Hey there. I remember being tentatively interested in Xapps, but I prefer to have most of my non-DE applications installed as Flatpaks, which means in many cases, I have been forced to use GNOME versions of applications that don't have better alternatives. Would you be interested in distributing Flatpak versions of the apps, be they in Flathub or your own repo?

**Comment by clefebvre** [comment]
Yes, we do it for some already. Warpinator for instance is available as Flatpak. It takes time so we do it when we really need to.

**Comment by HugLifeTiZ** [comment]
Why the instant close after comment? What is the criteria for "really need to"? Is it for when distros are badly lagging behind in packaging current versions, or they're not available at all?
